In [3]:
import pandas as pd
import numpy as np
from datetime import datetime
import pickle

In [26]:
def pred_func(current_time, arrival_hour_in, csv, carpark_array):
    df = pd.read_csv(csv)
    
    current_day = int(current_time.day)
    current_hour = int(current_time.hour)
    arrival_hour = current_hour + arrival_hour_in
    
    if arrival_hour > 24:
        arrival_hour -= 24
        current_day += 1
    
    predictions = []
    
    print("current day", current_day)
    print("arrival hour", arrival_hour)
    
    for carpark in carpark_array:
        carpark_df = df[df["carpark_number"] == carpark]
        print(carpark_df)
        day_df = carpark_df[carpark_df["day"] == current_day]
        final_df = day_df[day_df["hour"] == arrival_hour]
        
        filename = "models/model_" + carpark + ".sav"
        model = pickle.load(open(filename, 'rb'))
        
        prediction = model.predict([[current_day, arrival_hour, final_df['lag_1'].iloc[0], final_df['lag_168'].iloc[0]]])
        predictions.append(prediction)
        print("actual", final_df['percent_lots_available'])
        
    return predictions
        

#day, lag 1 col, lag168 col, hr
#current time (now.date), day, hr, get corresponding row from the df. use those values to predict the percentage lot available.

In [28]:
now = datetime.now()
preds = pred_func(now, 13, "oct_data_with_lags.csv", ['STM3', 'BM20', 'TE13', 'AV1'])
preds

current day 9
arrival hour 7
       carpark_number  hour  percent_lots_available  day  lag_1  lag_168
100080           STM3     0                0.000000    1    0.0      0.0
100081           STM3     1                0.000000    1    0.0      0.0
100082           STM3     2                0.000000    1    0.0      0.0
100083           STM3     3                0.000000    1    0.0      0.0
100084           STM3     4               14.090909    1    0.0      0.0
...               ...   ...                     ...  ...    ...      ...
100819           STM3    19                0.000000   31    0.0      0.0
100820           STM3    20                0.000000   31    0.0      0.0
100821           STM3    21                0.000000   31    0.0      0.0
100822           STM3    22                0.000000   31    0.0      0.0
100823           STM3    23                0.000000   31    0.0      0.0

[744 rows x 6 columns]
actual 100279    14.545455
Name: percent_lots_available, dtype: float64

C:\Users\wamik\anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator SVR from version 1.0.2 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\wamik\anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator SVR from version 1.0.2 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\wamik\anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator SVR from version 1.0.2 when using version 1.1.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:

[array([0.09957921]),
 array([60.0691467]),
 array([77.1395119]),
 array([75.4627124])]

In [29]:
def get_user_input():
    pd.set_option('display.max_rows', 100)
    user_pref = []
    
    df = pd.read_csv('landmark_locations.csv', index_col=False)
    
    print(df[['Landmark', 'Postal_Code']])
    print("\n")
    print("Enter the index of your preferred Landmark: ")
    
    user_loc = input()
    user_loc_int = int(user_loc)
    
    landmark = df.iloc[user_loc_int]['Landmark']
    postal_code = df.iloc[user_loc_int]['Postal_Code']
    
    user_pref.append(postal_code)
    
    output = "You have selected the following landmark: " + landmark + ", " + str(postal_code)
    
    print("\n")
    print(output)
    print("\n")
    print("How many hours from now will you reach your destination?")
    hour = input()
    
    user_pref.append(int(hour))
    
    return user_pref

In [30]:
get_user_input()

                                       Landmark  Postal_Code
0         Buddha Tooth Relic Temple and Museum.        58840
1                         Sri Mariamman Temple.        58793
2                           Maxwell Food Centre        69184
3                       Thian Hock Keng Temple.        68613
4                    Chinatown Heritage Centre.        59207
5                       Chinatown Street Market        58943
6                  Singapore Musical Box Museum        68619
7                             Chinatown Complex        50335
8                                 Masjid Jamae.        58767
9                         People's Park Complex        59108
10                              Masjid Al-Abrar        68635
11                       100 AM Shopping centre        79027
12                 Icon Village Shopping Centre        78877
13                   Bangladesh High Commission        89058
14                 Tanjong Pagar Community Club        89774
15                      

[68635, 2]